sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-dps-interest@amazon.com
services:
    - docker
jobs:
  include:
    - stage: build
      script: 
        - ./travis_build.sh
    - stage: performance testing
        - ./travis_performance_testing.sh
