sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  global:
    - BEFORE_BUILD_TARGET_WORKSPACE='git config --global user.email "avishaya@amazon.com" && git config --global user.name "AAlon"'
  matrix:
    - ROS_DISTRO="dashing"
install:
  - git clone -b colcon-rebase https://github.com/ipa-mdl/industrial_ci.git .ros_ci
script:
  - .ros_ci/travis.sh
